export function annualFinancialDemoFixture() {
  const solutions = [
    solution("chefq-demo-battery-250", 1, 250, 249800, 66000, 6.6, 2299.76),
    solution("chefq-demo-battery-300", 2, 300, 268800, 47000, 7.1, 2609.51),
    solution("chefq-demo-battery-389", 3, 389, 298600, 16000, 8.0, 3160.87),
  ];
  return {
    contract_version: "ci_annual_financial_demo_v2" as const,
    status: "ready" as const,
    analysis_mode: "invoice_derived_demo_financial_comparison" as const,
    project_id: "project-1",
    demo_only: true as const,
    analysis_modules: [
      { module_id: "evidence" as const, label: "Load & bill evidence", status: "ready" as const, detail: "Saved bill and measured interval coverage are available." },
      { module_id: "physical" as const, label: "Solar & battery physics", status: "demo_ready" as const, detail: "Solar-only and three battery offers are interval-tested." },
      { module_id: "tariff" as const, label: "Tariff replay", status: "input_required" as const, detail: "Retail, network and demand windows still require approved mapping." },
      { module_id: "finance" as const, label: "Annual finance", status: "demo_ready" as const, detail: "Quoted CAPEX, O&M, escalation, NPV, IRR and payback are modelled." },
      { module_id: "connection" as const, label: "Grid connection", status: "input_required" as const, detail: "DNSP inverter and export limits require a connection offer." },
      { module_id: "compliance" as const, label: "Site & compliance", status: "input_required" as const, detail: "Structural, fire, electrical, warranty and insurance review remains open." },
    ],
    common_system: {
      pv_capacity_kwp_dc: 141.7,
      pv_annual_specific_yield_kwh_per_kw: 1450,
      pv_derating_factor: 0.88,
      inverter_unit_count: 2,
      inverter_unit_capacity_kw_ac: 125,
      inverter_capacity_kw_ac: 250,
      battery_power_assumption_kw: 250,
      battery_round_trip_efficiency: 0.9,
      minimum_soc_fraction: 0.1,
      maximum_soc_fraction: 0.9,
      export_limit_kw: 0,
      export_rate_aud_per_kwh: 0,
    },
    evidence_basis: {
      retailer: "Origin Energy",
      billing_period_start: "2026-03-01",
      billing_period_end: "2026-03-31",
      billing_days: 31,
      invoice_consumption_kwh: 84484.22,
      invoice_subtotal_ex_gst_aud: 17818.68,
      annualised_consumption_kwh: 994734.84,
      annualised_baseline_cost_aud: 209795.73,
      measured_energy_year: 2025,
    },
    value_cases: {
      bill_blended: { label: "Bill-blended demo", rate_aud_per_kwh: 0.210907, included_bill_components: "All invoice charges", formal_tariff_result: false as const },
      conservative_energy_only: { label: "Energy-only sensitivity", rate_aud_per_kwh: 0.104497, included_bill_components: "Energy and environmental", formal_tariff_result: false as const },
    },
    tariff_inputs: {
      status: "awaiting_approved_window_mapping" as const,
      rates_applied_to_finance: false as const,
      demand_savings_applied: false as const,
      demand_savings_realisation_fraction: 0.85,
      retail_peak_c_per_kwh: 8.497,
      retail_off_peak_c_per_kwh: 6.9579,
      mlf: 1.0049,
      dlf: 1.0606,
      network_peak_c_per_kwh: 4.14,
      network_off_peak_c_per_kwh: 3.24,
      rolling_demand_aud_per_kva_month: 11.94,
      incentive_demand_aud_per_kva_month: 10.2,
      boundary: "Recorded but not monetised until tariff windows and kVA treatment are approved.",
    },
    assumptions: {
      currency: "AUD" as const,
      tax_basis: "supplied_total_assumed_ex_gst_for_demo" as const,
      price_source: "user_supplied_total_solution_prices" as const,
      discount_rate: 0.08,
      annual_value_degradation_rate: 0.005,
      annual_value_escalation_rate: 0.025,
      analysis_term_years: 15,
      solar_om_fraction_of_component_capex: 0.01,
      battery_om_fraction_of_component_capex: 0.015,
      solar_unit_cost_aud_per_kw: 530,
      battery_unit_cost_aud_per_kwh: 413,
      battery_inverter_total_aud: 20000,
      emissions_factor_kg_co2e_per_kwh: 0.79,
      replacement_events_aud: [] as [],
    },
    financial_review_order: { algorithm_id: "ci_demo_highest_bill_blended_npv_v2" as const, basis: "Highest demo NPV; not a recommendation.", leader_scenario_id: solutions[0].scenario_id, recommendation_permitted: false as const },
    commercial_readout: { headline: "250 kWh leads.", tradeoff: "Lower CAPEX leads this demo after annual O&M.", decision_boundary: "Demand tariff may change the order." },
    baseline_case: { label: "No system" as const, annualised_cost_aud: 209795.73, annualised_grid_import_kwh: 994734.84 },
    solar_only_case: {
      scenario_id: "chefq-demo-solar-only" as const,
      label: "Solar only" as const,
      pv_capacity_kwp_dc: 141.7,
      battery_capacity_kwh: 0 as const,
      first_year_value_aud: 38000,
      annualised_post_system_cost_aud: 171795.73,
      physical_outcome: physical(0, 180000, 0, 142.2),
      pricing_status: "installed_price_required" as const,
      financial_metrics_permitted: false as const,
      customer_facing_permission: false as const,
      recommendation_permitted: false as const,
    },
    solutions,
    currency_values_permitted: true as const,
    customer_facing_permission: false as const,
    recommendation_permitted: false as const,
    disclaimer: "Demo only; not an approved tariff result or customer recommendation.",
  };
}

function solution(id: string, rank: number, battery: number, capex: number, npv: number, payback: number, om: number) {
  const metrics = { net_present_value_aud: npv, payback_period_years: payback, internal_rate_of_return: 0.12, lifetime_net_value_undiscounted_aud: 180000, annual_cashflows_aud: Array(15).fill(40000) };
  const solar = 75101;
  const batteryComponent = battery * 413;
  const inverter = 20000;
  return {
    scenario_id: id,
    label: `${battery} kWh battery`,
    financial_review_rank: rank,
    pv_capacity_kwp_dc: 141.7,
    battery_capacity_kwh: battery,
    inverter_unit_count: 2,
    inverter_unit_capacity_kw_ac: 125,
    inverter_capacity_kw_ac: 250,
    upfront_cost_aud: capex,
    capex_breakdown: { solar_component_aud: solar, battery_component_aud: batteryComponent, battery_inverter_aud: inverter, balance_of_system_and_delivery_aud: capex - solar - batteryComponent - inverter, total_aud: capex },
    annual_om_cost_aud: om,
    first_year_value_aud: 40000,
    annualised_post_system_cost_aud: 169000,
    annualised_bill_reduction_percent: 19.1,
    metrics,
    conservative_sensitivity: { first_year_value_aud: 20000, metrics: { ...metrics, net_present_value_aud: -80000, payback_period_years: 13.2 } },
    physical_outcome: physical(battery, 190000, 4000, 150.1),
    customer_facing_permission: false as const,
    recommendation_permitted: false as const,
  };
}

function physical(battery: number, reduction: number, discharge: number, emissions: number) {
  return {
    energy_year: 2025,
    grid_import_reduction_kwh: reduction,
    grid_import_reduction_percent: 17.2,
    pv_generation_kwh: 187000,
    pv_self_consumption_percent: 99.5,
    battery_discharge_output_kwh: discharge,
    battery_equivalent_full_cycles: battery === 0 ? 0 : 12,
    baseline_peak_kw: 283,
    post_system_peak_kw: 250,
    peak_reduction_kw: 33,
    peak_reduction_percent: 11.7,
    avoided_emissions_t_co2e: emissions,
  };
}
